// Mocks generated by Mockito 5.4.6 from annotations
// in docscannerplus/test/unit/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:docscannerplus/models/cloud_file_metadata.dart' as _i5;
import 'package:docscannerplus/models/document_model.dart' as _i7;
import 'package:docscannerplus/repositories/cloud_repository.dart' as _i2;
import 'package:docscannerplus/repositories/document_repository.dart' as _i6;
import 'package:docscannerplus/services/analytics_service.dart' as _i8;
import 'package:docscannerplus/services/cloud/cloud_storage_service.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CloudRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudRepository extends _i1.Mock implements _i2.CloudRepository {
  MockCloudRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isEnabled),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> setProvider(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#setProvider, [providerId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> uploadFile(_i4.File? file, String? destinationName) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [file, destinationName]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i4.File?> downloadFile(String? cloudId, String? savePath) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [cloudId, savePath]),
            returnValue: _i3.Future<_i4.File?>.value(),
          )
          as _i3.Future<_i4.File?>);

  @override
  _i3.Future<void> deleteFile(String? cloudId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [cloudId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.CloudFileMetadata>> listFiles() =>
      (super.noSuchMethod(
            Invocation.method(#listFiles, []),
            returnValue: _i3.Future<List<_i5.CloudFileMetadata>>.value(
              <_i5.CloudFileMetadata>[],
            ),
          )
          as _i3.Future<List<_i5.CloudFileMetadata>>);
}

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i6.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> performMigrationIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#performMigrationIfNeeded, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.DocumentModel>> loadDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#loadDocuments, []),
            returnValue: _i3.Future<List<_i7.DocumentModel>>.value(
              <_i7.DocumentModel>[],
            ),
          )
          as _i3.Future<List<_i7.DocumentModel>>);

  @override
  _i3.Future<List<_i7.DocumentModel>> loadActiveDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#loadActiveDocuments, []),
            returnValue: _i3.Future<List<_i7.DocumentModel>>.value(
              <_i7.DocumentModel>[],
            ),
          )
          as _i3.Future<List<_i7.DocumentModel>>);

  @override
  _i3.Stream<List<_i7.DocumentModel>> watchActiveDocuments({
    int? limit,
    String? folderId,
    _i7.DocumentSortOption? sort,
    String? tag,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveDocuments, [], {
              #limit: limit,
              #folderId: folderId,
              #sort: sort,
              #tag: tag,
            }),
            returnValue: _i3.Stream<List<_i7.DocumentModel>>.empty(),
          )
          as _i3.Stream<List<_i7.DocumentModel>>);

  @override
  _i3.Future<List<_i7.DocumentModel>> loadTrashedDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrashedDocuments, []),
            returnValue: _i3.Future<List<_i7.DocumentModel>>.value(
              <_i7.DocumentModel>[],
            ),
          )
          as _i3.Future<List<_i7.DocumentModel>>);

  @override
  _i3.Future<void> saveDocuments(List<_i7.DocumentModel>? docs) =>
      (super.noSuchMethod(
            Invocation.method(#saveDocuments, [docs]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveNewDocument(_i7.DocumentModel? doc) =>
      (super.noSuchMethod(
            Invocation.method(#saveNewDocument, [doc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> moveToTrash(_i7.DocumentModel? doc) =>
      (super.noSuchMethod(
            Invocation.method(#moveToTrash, [doc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restoreFromTrash(_i7.DocumentModel? doc) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromTrash, [doc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument(_i7.DocumentModel? doc) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [doc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> emptyTrash() =>
      (super.noSuchMethod(
            Invocation.method(#emptyTrash, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cleanupExpiredTrash() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupExpiredTrash, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDocument(_i7.DocumentModel? updatedDoc) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [updatedDoc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.DocumentModel>> loadDocumentsInFolder(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#loadDocumentsInFolder, [folderId]),
            returnValue: _i3.Future<List<_i7.DocumentModel>>.value(
              <_i7.DocumentModel>[],
            ),
          )
          as _i3.Future<List<_i7.DocumentModel>>);

  @override
  _i3.Future<void> moveToFolder(_i7.DocumentModel? doc, String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#moveToFolder, [doc, folderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String?, int>> getDocumentCountByFolder() =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentCountByFolder, []),
            returnValue: _i3.Future<Map<String?, int>>.value(<String?, int>{}),
          )
          as _i3.Future<Map<String?, int>>);

  @override
  _i3.Future<void> importDownloadedDocument(
    _i4.File? tmpFile,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#importDownloadedDocument, [tmpFile, fileName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i8.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> logEvent({
    required String? name,
    Map<String, Object>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logEvent, [], {
              #name: name,
              #parameters: parameters,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logScreenView({
    required String? screenName,
    String? screenClass,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [], {
              #screenName: screenName,
              #screenClass: screenClass,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setUserProperty({
    required String? name,
    required String? value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserProperty, [], {
              #name: name,
              #value: value,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logDocumentScanned({
    required int? pageCount,
    bool? isAutoCaptured = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logDocumentScanned, [], {
              #pageCount: pageCount,
              #isAutoCaptured: isAutoCaptured,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logSyncCompleted({
    required int? uploadedCount,
    required int? downloadedCount,
    required int? durationMs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logSyncCompleted, [], {
              #uploadedCount: uploadedCount,
              #downloadedCount: downloadedCount,
              #durationMs: durationMs,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logFeatureUsed(String? featureName) =>
      (super.noSuchMethod(
            Invocation.method(#logFeatureUsed, [featureName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> logError(String? error, {String? stackTrace}) =>
      (super.noSuchMethod(
            Invocation.method(#logError, [error], {#stackTrace: stackTrace}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [CloudStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudStorageService extends _i1.Mock
    implements _i9.CloudStorageService {
  MockCloudStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get providerId =>
      (super.noSuchMethod(
            Invocation.getter(#providerId),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#providerId),
            ),
          )
          as String);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  _i3.Future<bool> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getUserEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getUserEmail, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> uploadFile(_i4.File? file, String? destinationName) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [file, destinationName]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i4.File?> downloadFile(String? cloudId, String? savePath) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [cloudId, savePath]),
            returnValue: _i3.Future<_i4.File?>.value(),
          )
          as _i3.Future<_i4.File?>);

  @override
  _i3.Future<void> deleteFile(String? cloudId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [cloudId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.CloudFileMetadata>> listFiles() =>
      (super.noSuchMethod(
            Invocation.method(#listFiles, []),
            returnValue: _i3.Future<List<_i5.CloudFileMetadata>>.value(
              <_i5.CloudFileMetadata>[],
            ),
          )
          as _i3.Future<List<_i5.CloudFileMetadata>>);
}
