// Mocks generated by Mockito 5.4.6 from annotations
// in docscannerplus/test/widget/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:docscannerplus/models/document_model.dart' as _i4;
import 'package:docscannerplus/models/folder_model.dart' as _i7;
import 'package:docscannerplus/repositories/document_repository.dart' as _i2;
import 'package:docscannerplus/repositories/folder_repository.dart' as _i6;
import 'package:docscannerplus/repositories/settings_repository.dart' as _i8;
import 'package:docscannerplus/services/ocr_service.dart' as _i11;
import 'package:flutter/material.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDocumentRepository extends _i1.Mock
    implements _i2.DocumentRepository {
  MockDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> performMigrationIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#performMigrationIfNeeded, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.DocumentModel>> loadDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#loadDocuments, []),
            returnValue: _i3.Future<List<_i4.DocumentModel>>.value(
              <_i4.DocumentModel>[],
            ),
          )
          as _i3.Future<List<_i4.DocumentModel>>);

  @override
  _i3.Future<List<_i4.DocumentModel>> loadActiveDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#loadActiveDocuments, []),
            returnValue: _i3.Future<List<_i4.DocumentModel>>.value(
              <_i4.DocumentModel>[],
            ),
          )
          as _i3.Future<List<_i4.DocumentModel>>);

  @override
  _i3.Stream<List<_i4.DocumentModel>> watchActiveDocuments({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveDocuments, [], {#limit: limit}),
            returnValue: _i3.Stream<List<_i4.DocumentModel>>.empty(),
          )
          as _i3.Stream<List<_i4.DocumentModel>>);

  @override
  _i3.Future<List<_i4.DocumentModel>> loadDocumentsInFolder(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#loadDocumentsInFolder, [folderId]),
            returnValue: _i3.Future<List<_i4.DocumentModel>>.value(
              <_i4.DocumentModel>[],
            ),
          )
          as _i3.Future<List<_i4.DocumentModel>>);

  @override
  _i3.Future<List<_i4.DocumentModel>> loadTrashedDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#loadTrashedDocuments, []),
            returnValue: _i3.Future<List<_i4.DocumentModel>>.value(
              <_i4.DocumentModel>[],
            ),
          )
          as _i3.Future<List<_i4.DocumentModel>>);

  @override
  _i3.Future<void> saveDocuments(List<_i4.DocumentModel>? docs) =>
      (super.noSuchMethod(
            Invocation.method(#saveDocuments, [docs]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveNewDocument(_i4.DocumentModel? doc) =>
      (super.noSuchMethod(
            Invocation.method(#saveNewDocument, [doc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> moveToTrash(_i4.DocumentModel? doc) =>
      (super.noSuchMethod(
            Invocation.method(#moveToTrash, [doc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> restoreFromTrash(_i4.DocumentModel? doc) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromTrash, [doc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDocument(_i4.DocumentModel? doc) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [doc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> emptyTrash() =>
      (super.noSuchMethod(
            Invocation.method(#emptyTrash, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cleanupExpiredTrash() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupExpiredTrash, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateDocument(_i4.DocumentModel? updatedDoc) =>
      (super.noSuchMethod(
            Invocation.method(#updateDocument, [updatedDoc]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> moveToFolder(_i4.DocumentModel? doc, String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#moveToFolder, [doc, folderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String?, int>> getDocumentCountByFolder() =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentCountByFolder, []),
            returnValue: _i3.Future<Map<String?, int>>.value(<String?, int>{}),
          )
          as _i3.Future<Map<String?, int>>);

  @override
  _i3.Future<void> importDownloadedDocument(
    _i5.File? tmpFile,
    String? fileName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#importDownloadedDocument, [tmpFile, fileName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FolderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFolderRepository extends _i1.Mock implements _i6.FolderRepository {
  MockFolderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.FolderModel>> loadFolders() =>
      (super.noSuchMethod(
            Invocation.method(#loadFolders, []),
            returnValue: _i3.Future<List<_i7.FolderModel>>.value(
              <_i7.FolderModel>[],
            ),
          )
          as _i3.Future<List<_i7.FolderModel>>);

  @override
  _i3.Future<void> saveFolders(List<_i7.FolderModel>? folders) =>
      (super.noSuchMethod(
            Invocation.method(#saveFolders, [folders]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addFolder(_i7.FolderModel? folder) =>
      (super.noSuchMethod(
            Invocation.method(#addFolder, [folder]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateFolder(_i7.FolderModel? updatedFolder) =>
      (super.noSuchMethod(
            Invocation.method(#updateFolder, [updatedFolder]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteFolder(String? folderId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFolder, [folderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i8.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveThemeMode(_i9.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#saveThemeMode, [mode]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i9.ThemeMode loadThemeMode() =>
      (super.noSuchMethod(
            Invocation.method(#loadThemeMode, []),
            returnValue: _i9.ThemeMode.system,
          )
          as _i9.ThemeMode);

  @override
  _i3.Future<void> saveDefaultFilter(String? filterName) =>
      (super.noSuchMethod(
            Invocation.method(#saveDefaultFilter, [filterName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String loadDefaultFilter() =>
      (super.noSuchMethod(
            Invocation.method(#loadDefaultFilter, []),
            returnValue: _i10.dummyValue<String>(
              this,
              Invocation.method(#loadDefaultFilter, []),
            ),
          )
          as String);

  @override
  _i3.Future<void> saveAutoSaveToGallery(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#saveAutoSaveToGallery, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool loadAutoSaveToGallery() =>
      (super.noSuchMethod(
            Invocation.method(#loadAutoSaveToGallery, []),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> saveHapticFeedback(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#saveHapticFeedback, [enabled]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  bool loadHapticFeedback() =>
      (super.noSuchMethod(
            Invocation.method(#loadHapticFeedback, []),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> saveCloudProvider(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#saveCloudProvider, [providerId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> getCloudEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#getCloudEnabled, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}

/// A class which mocks [OcrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOcrService extends _i1.Mock implements _i11.OcrService {
  MockOcrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> extractText(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#extractText, [imagePath]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
