// Mocks generated by Mockito 5.4.6 from annotations
// in docscannerplus/test/integration/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:docscannerplus/repositories/cloud_repository.dart' as _i2;
import 'package:docscannerplus/services/cloud/cloud_storage_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CloudRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudRepository extends _i1.Mock implements _i2.CloudRepository {
  MockCloudRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isEnabled),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> setProvider(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#setProvider, [providerId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> uploadFile(_i4.File? file, String? destinationName) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [file, destinationName]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i4.File?> downloadFile(String? cloudId, String? savePath) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [cloudId, savePath]),
            returnValue: _i3.Future<_i4.File?>.value(),
          )
          as _i3.Future<_i4.File?>);

  @override
  _i3.Future<void> deleteFile(String? cloudId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [cloudId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> listFiles() =>
      (super.noSuchMethod(
            Invocation.method(#listFiles, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);
}

/// A class which mocks [CloudStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudStorageService extends _i1.Mock
    implements _i5.CloudStorageService {
  MockCloudStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get providerId =>
      (super.noSuchMethod(
            Invocation.getter(#providerId),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#providerId),
            ),
          )
          as String);

  @override
  String get displayName =>
      (super.noSuchMethod(
            Invocation.getter(#displayName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#displayName),
            ),
          )
          as String);

  @override
  _i3.Future<bool> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<String?> getUserEmail() =>
      (super.noSuchMethod(
            Invocation.method(#getUserEmail, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> uploadFile(_i4.File? file, String? destinationName) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [file, destinationName]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i4.File?> downloadFile(String? cloudId, String? savePath) =>
      (super.noSuchMethod(
            Invocation.method(#downloadFile, [cloudId, savePath]),
            returnValue: _i3.Future<_i4.File?>.value(),
          )
          as _i3.Future<_i4.File?>);

  @override
  _i3.Future<void> deleteFile(String? cloudId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [cloudId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, String>> listFiles() =>
      (super.noSuchMethod(
            Invocation.method(#listFiles, []),
            returnValue: _i3.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i3.Future<Map<String, String>>);
}
